swagger: '2.0'
info:
  title: API Gateway
  description: API Gateway for Authentication and ChatGPT functions
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /token:
    post:
      summary: Authentication endpoint
      operationId: auth
      x-google-backend:
        address: ${authentication_function}/token
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /refresh-token:
    post:
      summary: Refresh token endpoint
      operationId: refreshToken
      x-google-backend:
        address: ${authentication_function}/refresh-token
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
  /chat:
    post:
      summary: ChatGPT endpoint
      operationId: chat
      x-google-backend:
        address: ${chatgpt_function}
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '429':
          description: Too many requests
        '500':
          description: Internal server error